server:
  port: 80
spring:
  application:
    name: cloud-sonsumer-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群配置
  instance:
    instance-id: payment80
    prefer-ip-address: true