server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7002
eureka:
  instance:
    hostname:eureka7002.com
  client:
    #false表示不想服务中心注册自己
    register-with-eureka: false
    #false表示自己端 就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/